#!/usr/bin/env bash

#=============================================================================|
# must not have the rsh-server package installed                              |
#=============================================================================|

#set control_check variable
subject="rsh-server"
control_check=$(dpkg -l | grep $subject 2>/dev/null)

if [[ -z "$control_check" ]]; then
        echo "Control Passed"
else
        echo "Control Failed"
        echo "You must remove $subject"
fi

